In [1]:
import tensorflow as tf
from PIL import Image
import numpy as np

In [2]:
filenames = ['./data/img/cropped/001.png', './data/img/cropped/002.png', './data/img/cropped/003.png']
filename_queue_img = tf.train.string_input_producer(filenames)
img_record = 3
filename_queue_description = tf.train.string_input_producer(['./data/description/raw_data.csv'])
num_record = 50

In [3]:
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue_img)
images = tf.image.decode_png(value, channels=3)

In [4]:
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    for i in range(img_record):
        image = sess.run(images)
        print(sess.run(tf.shape(image)))
#         Image.fromarray(np.asarray(image)).show()

    coord.request_stop()
    coord.join(threads)
    sess.close()

[200 200   3]
[200 200   3]
[200 200   3]


In [5]:
reader = tf.TextLineReader()
key,value = reader.read(filename_queue_description)
record_defaults =[[-1], [-1], [-1], [-1], [-1], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2], [-2]]
lab1, lab2, lab3, lab4, lab5, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15 = tf.decode_csv(value, record_defaults)  

feautre_label = tf.stack([lab1, lab2, lab3, lab4, lab5])
feature_word = tf.stack([w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15])

In [15]:
with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)

    for i in range(num_record):
        label, raw_word = sess.run([feautre_label, feature_word])
        onehot = tf.one_hot(indices=raw_word, depth=27)
#         print(sess.run(onehot))
    coord.request_stop()
    coord.join(threads)
    sess.close()